export default {
  phonepeMerchantDetails: [],
  phonepeCompletedDetails:[],
  phonepeDate:[],
  updateRemarks:[],
  staticNewRequestsLead:[],
  phonepePaperRoll:[],
  updatePodNumber:[],
  staticReferBackLead:[],
  updateSacnQRNumber:[],
  staticCourierLead:[],
  updateSacnSoundBoxNumber:[],
  paperPdf:[],
  phonepeCompletedPaperRoll:[],
  phonepeRtoTicket:[],
  attemptLog:[],
  optionsList: [],
  resolutionList:[],
  fetchIssueList:[],
  fetchActionList:[],
 viewlogs:[],
};
